In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("property_prices_v2.csv")
df.sample(5)

,area,bedrooms,price
47,1420,3,326120
95,1524,3,358336
81,1412,3,359205
35,2145,4,453484
68,595,1,151408


In [3]:
from sklearn import preprocessing

sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_X = sx.fit_transform(df.drop('price', axis=1))
scaled_y = sy.fit_transform(df['price'].values.reshape(-1, 1))

In [4]:
scaled_X

array([[0.40384615, 0.5       ],
       [0.9408284 , 1.        ],
       [0.68392505, 0.75      ],
       [0.49161736, 0.5       ],
       [0.20118343, 0.25      ],
       [0.22287968, 0.25      ],
       [0.16962525, 0.        ],
       [0.67948718, 0.75      ],
       [0.61193294, 0.5       ],
       [0.77071006, 0.75      ],
       [0.09220907, 0.        ],
       [0.88412229, 1.        ],
       [0.64053254, 0.75      ],
       [0.25986193, 0.25      ],
       [0.18984221, 0.25      ],
       [0.19329389, 0.25      ],
       [0.18195266, 0.25      ],
       [0.45167653, 0.5       ],
       [0.53402367, 0.5       ],
       [0.26775148, 0.25      ],
       [0.49260355, 0.5       ],
       [0.21794872, 0.25      ],
       [0.31558185, 0.25      ],
       [0.40532544, 0.5       ],
       [0.4566075 , 0.5       ],
       [0.59220907, 0.75      ],
       [0.2061144 , 0.25      ],
       [0.59023669, 0.5       ],
       [0.43885602, 0.5       ],
       [0.1183432 , 0.        ],
       [0.

In [5]:
scaled_y

array([[0.41790292],
       [0.94829258],
       [0.68258314],
       [0.4802157 ],
       [0.1801114 ],
       [0.25986797],
       [0.19089634],
       [0.64811229],
       [0.57236898],
       [0.76834696],
       [0.04022482],
       [0.91366976],
       [0.68496854],
       [0.21031109],
       [0.21494374],
       [0.24312414],
       [0.25784637],
       [0.43650949],
       [0.51164954],
       [0.27336988],
       [0.49455802],
       [0.27745223],
       [0.29646864],
       [0.47143854],
       [0.44139311],
       [0.61848361],
       [0.28690172],
       [0.50529462],
       [0.50103498],
       [0.06824404],
       [0.43620326],
       [0.25764836],
       [0.06492843],
       [0.88163957],
       [0.84341794],
       [0.70025489],
       [0.30708551],
       [0.0192789 ],
       [0.51127884],
       [0.55210921],
       [0.24384022],
       [0.46527012],
       [0.11373469],
       [0.89649075],
       [0.36735826],
       [0.44840194],
       [0.32361291],
       [0.406

In [7]:
w = np.ones(shape=(2))

array([0.90384615, 1.9408284 , 1.43392505, 0.99161736, 0.45118343,
       0.47287968, 0.16962525, 1.42948718, 1.11193294, 1.52071006,
       0.09220907, 1.88412229, 1.39053254, 0.50986193, 0.43984221,
       0.44329389, 0.43195266, 0.95167653, 1.03402367, 0.51775148,
       0.99260355, 0.46794872, 0.56558185, 0.90532544, 0.9566075 ,
       1.34220907, 0.4561144 , 1.09023669, 0.93885602, 0.1183432 ,
       0.88658777, 0.47879684, 0.        , 1.93491124, 1.90828402,
       1.53994083, 0.5887574 , 0.04142012, 1.0443787 , 1.10601578,
       0.53944773, 0.96646943, 0.08925049, 1.95710059, 0.61143984,
       1.01232742, 0.64546351, 0.93244576, 0.92998028, 0.65285996,
       1.8821499 , 1.44773176, 1.94428008, 1.41765286, 1.09763314,
       1.9699211 , 0.04585799, 0.58234714, 0.05966469, 0.53648915,
       1.02416174, 0.54092702, 1.40483235, 0.94773176, 0.65384615,
       1.02810651, 0.60996055, 1.39891519, 0.02564103, 2.        ,
       1.43491124, 0.5142998 , 0.03402367, 1.47682446, 1.56508

In [ ]:
def batch_gradient_descent(X, y_true, epochs, learning_rate=0.01):
    number_of_features = X.shape[1]
    
    w = np.ones(shape=(number_of_features, 1))
    b = 0
    total_samples = X.shape[0]

    for i in range(epochs):
        y_predicted = np.dot(w, scaled_X.T) + bias